

@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: SplashScreen, initial: true),
    AutoRoute(page: DashboardView, name: 'Dashboard'),
    AutoRoute(page: AdDetailScreen, path: '/AdDetailScreen/:adId'),
    AutoRoute(page: ChatHome, name: 'ChatHome'),
    AutoRoute(page: SignInPageMain, name: 'SignInPage'),
    AutoRoute(page: MyProfileView, name: 'MyProfile'),
    AutoRoute(page: CreateAdSimpleView,name: 'CreateAds'),
    AutoRoute(page: SimpleAddCarView,name: 'SimpleCreateAdView'),
    AutoRoute(page: PageNotFound, path: '/404'),
    AutoRoute(page: MyGaragePage,name: 'MyGarage'),
    AutoRoute(page: SearchPageMainWidget,name: 'SearchPage'),
    AutoRoute(page: ChatPage,name: 'ChatPage'),
    AutoRoute(page: FullScreenImageView,name: 'FullImageView'),
    AutoRoute(page: PanoramaImageViewer,name: 'PanaromaImageView'),
    AutoRoute(page: CommentsScreen,name: 'CommentsPage'),
    AutoRoute(page: DocumentHomePage,name: 'DocumentHomePage'),
    AutoRoute(page: LogoutScreen,name: 'LogoutPage'),
    AutoRoute(page: Onboarding,name: 'OnboardingPage'),
    AutoRoute(page: PlateNumberSearchPage,name: 'PlateNumberSearchPage'),
    AutoRoute(page: CompareCarsView,name: 'CompareCarsView'),
    AutoRoute(page: BeaconListingView,name: 'BeaconListingView'),
    AutoRoute(page: FolderHomePage,name: 'FolderHomePage'),
    AutoRoute(page: AddFolderView,name: 'AddFolderView'),
    AutoRoute(page: SearchAdvancePage, name: 'SearchAdvancePage'),
    AutoRoute(page: SomeoneProfileView, name: 'SomeoneProfileView'),
    AutoRoute(page: SomeoneReviewsView, name: 'SomeoneReviewsView'),
    AutoRoute(page: EditProfileView, name: 'EditProfileView'),
    AutoRoute(page: BadgesView, name: 'BadgesView'),
    AutoRoute(page: MyWalletView, name: 'MyWalletView'),
    AutoRoute(page: SettingsView, name: 'SettingsView'),
    AutoRoute(page: UserVerficationView, name: 'UserVerficationView'),
    AutoRoute(page: ContactUsView, name: 'ContactUsView'), 
    AutoRoute(page: SecurityLoginView, name: 'SecurityLoginView'),
    AutoRoute(page: DiscussionView, name: 'DiscussionView'),
  ],
)
class $Router {}
